### ISSUE TITLE
url not set

### ISSUE THREAD

**Issue by wjt123125** [heiwais25/LuckysheetServer#1]
请教一下，这个问题怎么解决，luckysheet官方无人回复,
有找到相似问题，但是具体还是不知道怎么解决
https://github.com/mengshukeji/LuckysheetServer/issues/9
<img width="425" alt="图片" src="https://user-images.githubusercontent.com/31788078/173385416-f5952573-7fb9-4943-a0d8-3cd6958016b8.png">

```
java.sql.SQLException: url not set
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:888)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1369)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1365)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:109)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:612)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:700)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:712)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:783)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:804)
	at com.xc.luckysheet.postgres.impl.RecordSelectHandle.getFirstBlockIndexByGridKey(RecordSelectHandle.java:53)
	at com.xc.luckysheet.postgres.impl.RecordSelectHandle$$FastClassBySpringCGLIB$$9f89658f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:750)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.xc.luckysheet.postgres.impl.RecordSelectHandle$$EnhancerBySpringCGLIB$$424e7150.getFirstBlockIndexByGridKey(<generated>)
	at com.xc.luckysheet.db.server.JfGridFileGetService.getDefaultByGridKey(JfGridFileGetService.java:64)
	at com.xc.luckysheet.controller.JfGridFileController.load(JfGridFileController.java:68)
```

**Comment by wjt123125** [comment]
已解决，遇到相同问题的朋友可留言

**Comment by sunkeWEB** [comment]
你好，想问下你怎么解决的

**Comment by wjt123125** [comment]
我艹，忘记了

**Comment by sunkeWEB** [comment]
我看现在拉代码都没得dev配置，他现在是以数据库类型为配置文件

**Comment by wjt123125** [comment]
兄弟，这个luckysheetserver有很多问题的，我之前搞的时候发现了很多bug。

**Comment by sunkeWEB** [comment]
后面还用这个没？

**Comment by sunkeWEB** [comment]
主要是看起都不怎么维护了

**Comment by wjt123125** [comment]
在用，就是这个2.0版本的server不仅官方不提供，就是提供他也要商业化搞钱的。

**Comment by sunkeWEB** [comment]
难受了，请问下你这边还用什么推荐的产品使用下

**Comment by wjt123125** [comment]
我了解的好像，现在就只有这个

**Comment by sunkeWEB** [comment]
好的，谢谢了 我在研究下

**Comment by wjt123125** [comment]
我把我改的代码给你吧，加我微信：wjt123126
